
[project]
name = "memepool"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.counter]
# path = "contracts/counter.clar"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet

# Contracts

[contracts.amm-registry]
path = 'contracts/amm-registry.clar'
clarity_version = 2
epoch = 2.4

[contracts.amm-vault]
path = 'contracts/amm-vault.clar'
clarity_version = 2
epoch = 2.4

[contracts.auth]
path = 'contracts/auth.clar'
clarity_version = 2
epoch = 2.4

[contracts.fpmm]
path = 'contracts/fpmm.clar'
clarity_version = 2
epoch = 2.4

[contracts.semi-fungible-token]
path = 'contracts/tokens/semi-fungible-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.wagmi]
path = 'contracts/tokens/wagmi.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip-010-trait]
path = 'contracts/traits/sip-010-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.trait-flash-loan-user]
path = 'contracts/traits/trait-flash-loan-user.clar'
clarity_version = 2
epoch = 2.4


[contracts.sip013-semi-fungible-token-trait]
path = 'contracts/traits/sip013-semi-fungible-token-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip013-transfer-many-trait]
path = 'contracts/traits/sip013-transfer-many-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.token-amm-pool]
path = 'contracts/token-amm-pool.clar'
clarity_version = 2
epoch = 2.4

